metadata:
  # 名字必须与下面的spec字段匹配，并且格式为 <名称的复数形式>.<组名>
  name: redises.stable.example.com
spec:
  # 组名称 用于REST API /apis/<组>/<版本>
  group: stable.example.com
  versions:
    - name: v1beta1
      # 每个版本都可以通过served标志来独立启用或禁止
      served: true
      # 其中一个且只有一个版本必须被标记为存储版本？
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                port:
                  type: integer
                targetPort:
                  type: integer
                password:
                  type: string
  scoped: Namespaced
  names:
    # 名称的复数形式，用于URL:/apis/<组>/<版本>/<名称的复数形式>
    plural: redises
    # 名称的单数形式 作为命令行使用时和显示时的别名
    singular: redis
    # kind 通常是单数形式的驼峰命名形式，你的资源清单会使用这一形式
    kind: Redis
    # shortNames 允许你在命令行使用较短的字符串来匹配资源
    shortNames:
    - rds
